import type { Metadata } from "next";
import { daysOneFont } from "./ui/font";
import "./globals.css";
import NavBar from "./ui/nav-bar";

export const metadata: Metadata = {
  title: "Create Next App",//a changer
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={daysOneFont.className}>
        <NavBar />
        {children}
      </body>
    </html>
  );
}
